{"ast":null,"code":"var _jsxFileName = \"/Users/edhuezo-lopez/Desktop/hack4impact/bootcamp-project-2022/src/components/Home.tsx\",\n  _s = $RefreshSig$();\nimport RecipePreview from './recipePreview';\nimport recipes from '../recipeData';\nimport { useState, useEffect } from 'react';\nimport { jsxDEV as _jsxDEV } from \"react/jsx-dev-runtime\";\nexport default function Home() {\n  _s();\n  const [externalRecipes, setExternalRecipes] = useState([]);\n\n  //if i want to get rid of the error in the console, need to implement a try and catch\n  useEffect(() => {\n    //was missing the endpoint part aka the recipe after '/'\n    fetch(\"https://bootcamp-milestone-4.onrender.com/recipe\").then(recipes => recipes.json()).then(data => setExternalRecipes(data));\n    console.log(\"this should show up after the promise\");\n  }, []);\n  console.log(\"running preview\");\n  let allRecipes = [...recipes, ...externalRecipes];\n  return /*#__PURE__*/_jsxDEV(\"div\", {\n    children: allRecipes.map(recipe => /*#__PURE__*/_jsxDEV(RecipePreview, {\n      name: recipe.name,\n      description: recipe.description,\n      image: recipe.image,\n      ingredients: recipe.ingredients,\n      instructions: recipe.instructions\n    }, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 32,\n      columnNumber: 7\n    }, this))\n  }, void 0, false, {\n    fileName: _jsxFileName,\n    lineNumber: 30,\n    columnNumber: 7\n  }, this);\n}\n_s(Home, \"cLWvE/4GSMDKdwvhAtghqHHBlFA=\");\n_c = Home;\nvar _c;\n$RefreshReg$(_c, \"Home\");","map":{"version":3,"names":["RecipePreview","recipes","useState","useEffect","Home","externalRecipes","setExternalRecipes","fetch","then","json","data","console","log","allRecipes","map","recipe","name","description","image","ingredients","instructions"],"sources":["/Users/edhuezo-lopez/Desktop/hack4impact/bootcamp-project-2022/src/components/Home.tsx"],"sourcesContent":["import RecipePreview from './recipePreview';\nimport recipes, { Recipe } from '../recipeData';\nimport { useState, useEffect } from 'react';\n\n\nexport default function Home() {\n\n\n  const[externalRecipes, setExternalRecipes] = useState<Recipe[]>([]);\n\n  //if i want to get rid of the error in the console, need to implement a try and catch\n  useEffect(() => {\n    //was missing the endpoint part aka the recipe after '/'\n      fetch(\"https://bootcamp-milestone-4.onrender.com/recipe\")\n      .then((recipes) => recipes.json())\n      .then((data) => setExternalRecipes(data));\n      console.log(\"this should show up after the promise\")\n\n\n\n  }, []);\n\n    console.log(\"running preview\")\n\n    \n    let allRecipes = [...recipes, ...externalRecipes]\n  \n    return (\n\n      <div> \n          {allRecipes.map((recipe) => (\n      <RecipePreview\n      name={recipe.name}\n      description={recipe.description}\n      image={recipe.image}\n      ingredients={recipe.ingredients}\n      instructions={recipe.instructions}\n    />\n    ))}\n\n    </div>\n\n        \n\n\n\n    );\n    }"],"mappings":";;AAAA,OAAOA,aAAa,MAAM,iBAAiB;AAC3C,OAAOC,OAAO,MAAkB,eAAe;AAC/C,SAASC,QAAQ,EAAEC,SAAS,QAAQ,OAAO;AAAC;AAG5C,eAAe,SAASC,IAAI,GAAG;EAAA;EAG7B,MAAK,CAACC,eAAe,EAAEC,kBAAkB,CAAC,GAAGJ,QAAQ,CAAW,EAAE,CAAC;;EAEnE;EACAC,SAAS,CAAC,MAAM;IACd;IACEI,KAAK,CAAC,kDAAkD,CAAC,CACxDC,IAAI,CAAEP,OAAO,IAAKA,OAAO,CAACQ,IAAI,EAAE,CAAC,CACjCD,IAAI,CAAEE,IAAI,IAAKJ,kBAAkB,CAACI,IAAI,CAAC,CAAC;IACzCC,OAAO,CAACC,GAAG,CAAC,uCAAuC,CAAC;EAIxD,CAAC,EAAE,EAAE,CAAC;EAEJD,OAAO,CAACC,GAAG,CAAC,iBAAiB,CAAC;EAG9B,IAAIC,UAAU,GAAG,CAAC,GAAGZ,OAAO,EAAE,GAAGI,eAAe,CAAC;EAEjD,oBAEE;IAAA,UACKQ,UAAU,CAACC,GAAG,CAAEC,MAAM,iBAC3B,QAAC,aAAa;MACd,IAAI,EAAEA,MAAM,CAACC,IAAK;MAClB,WAAW,EAAED,MAAM,CAACE,WAAY;MAChC,KAAK,EAAEF,MAAM,CAACG,KAAM;MACpB,WAAW,EAAEH,MAAM,CAACI,WAAY;MAChC,YAAY,EAAEJ,MAAM,CAACK;IAAa;MAAA;MAAA;MAAA;IAAA,QAEnC;EAAC;IAAA;IAAA;IAAA;EAAA,QAEI;AAON;AAAC,GA1CmBhB,IAAI;AAAA,KAAJA,IAAI;AAAA;AAAA"},"metadata":{},"sourceType":"module","externalDependencies":[]}