{"ast":null,"code":"var _jsxFileName = \"/Users/edhuezo-lopez/Desktop/hack4impact/bootcamp-project-2022/frontend/src/components/Home.tsx\",\n  _s = $RefreshSig$();\nimport RecipePreview from './recipePreview';\nimport { useState, useEffect } from 'react';\nimport React from 'react';\nimport { jsxDEV as _jsxDEV } from \"react/jsx-dev-runtime\";\nexport default function Home() {\n  _s();\n  const [externalRecipes, setExternalRecipes] = useState([]);\n\n  //if i want to get rid of the error in the console, need to implement a try and catch\n  useEffect(() => {\n    //fetch(\"https://bootcamp-milestone-4.onrender.com/recipe\")\n    fetch(\"http://localhost:3001/recipe\").then(recipes => recipes.json()).then(data => setExternalRecipes(data));\n  }, []);\n  return /*#__PURE__*/_jsxDEV(\"div\", {\n    children: externalRecipes.map(recipe => /*#__PURE__*/_jsxDEV(RecipePreview, {\n      name: recipe.name,\n      description: recipe.description,\n      image: recipe.image,\n      ingredients: recipe.ingredients,\n      instructions: recipe.instructions,\n      external: true\n    }, void 0, false, {\n      fileName: _jsxFileName,\n      lineNumber: 40,\n      columnNumber: 15\n    }, this))\n  }, void 0, false, {\n    fileName: _jsxFileName,\n    lineNumber: 25,\n    columnNumber: 7\n  }, this);\n}\n_s(Home, \"cLWvE/4GSMDKdwvhAtghqHHBlFA=\");\n_c = Home;\nvar _c;\n$RefreshReg$(_c, \"Home\");","map":{"version":3,"names":["RecipePreview","useState","useEffect","React","Home","externalRecipes","setExternalRecipes","fetch","then","recipes","json","data","map","recipe","name","description","image","ingredients","instructions"],"sources":["/Users/edhuezo-lopez/Desktop/hack4impact/bootcamp-project-2022/frontend/src/components/Home.tsx"],"sourcesContent":["import RecipePreview from './recipePreview';\nimport recipes, { Recipe } from '../recipeData';\nimport { useState, useEffect } from 'react';\nimport React from 'react';\n\n\nexport default function Home() {\n\n\n  const[externalRecipes, setExternalRecipes] = useState<Recipe[]>([]);\n\n  //if i want to get rid of the error in the console, need to implement a try and catch\n  useEffect(() => {\n      //fetch(\"https://bootcamp-milestone-4.onrender.com/recipe\")\n      fetch(\"http://localhost:3001/recipe\")\n      .then((recipes) => recipes.json())\n      .then((data) => setExternalRecipes(data));\n      \n  \n  }, []);\n\n\n  \n    return (\n      <div> \n      {/*}\n      \n          {recipes.map((recipe) => (\n      <RecipePreview\n              name={recipe.name}\n              description={recipe.description}\n              image={recipe.image}\n              ingredients={recipe.ingredients}\n              instructions={recipe.instructions} external={false}                  />\n    ))}\n          {*/}\n\n\n        {externalRecipes.map((recipe) => (\n              <RecipePreview\n            name={recipe.name}\n            description={recipe.description}\n            image={recipe.image}\n            ingredients={recipe.ingredients}\n            instructions={recipe.instructions} external={true}                        />\n    ))}\n\n\n    </div>\n\n        \n\n\n\n    );\n    }"],"mappings":";;AAAA,OAAOA,aAAa,MAAM,iBAAiB;AAE3C,SAASC,QAAQ,EAAEC,SAAS,QAAQ,OAAO;AAC3C,OAAOC,KAAK,MAAM,OAAO;AAAC;AAG1B,eAAe,SAASC,IAAI,GAAG;EAAA;EAG7B,MAAK,CAACC,eAAe,EAAEC,kBAAkB,CAAC,GAAGL,QAAQ,CAAW,EAAE,CAAC;;EAEnE;EACAC,SAAS,CAAC,MAAM;IACZ;IACAK,KAAK,CAAC,8BAA8B,CAAC,CACpCC,IAAI,CAAEC,OAAO,IAAKA,OAAO,CAACC,IAAI,EAAE,CAAC,CACjCF,IAAI,CAAEG,IAAI,IAAKL,kBAAkB,CAACK,IAAI,CAAC,CAAC;EAG7C,CAAC,EAAE,EAAE,CAAC;EAIJ,oBACE;IAAA,UAcGN,eAAe,CAACO,GAAG,CAAEC,MAAM,iBACtB,QAAC,aAAa;MAChB,IAAI,EAAEA,MAAM,CAACC,IAAK;MAClB,WAAW,EAAED,MAAM,CAACE,WAAY;MAChC,KAAK,EAAEF,MAAM,CAACG,KAAM;MACpB,WAAW,EAAEH,MAAM,CAACI,WAAY;MAChC,YAAY,EAAEJ,MAAM,CAACK,YAAa;MAAC,QAAQ,EAAE;IAAK;MAAA;MAAA;MAAA;IAAA,QACzD;EAAC;IAAA;IAAA;IAAA;EAAA,QAGI;AAON;AAAC,GAjDmBd,IAAI;AAAA,KAAJA,IAAI;AAAA;AAAA"},"metadata":{},"sourceType":"module","externalDependencies":[]}